name: Build AudioTTo

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: 
          #- ubuntu-latest
          #- windows-latest
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.11"
          activate-environment: build-env

      - name: Install dependencies and pyinstaller
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download FFmpeg (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y ffmpeg
          mkdir -p bin
          cp /usr/bin/ffmpeg bin/ffmpeg
          cp /usr/bin/ffprobe bin/ffprobe

      - name: Download FFmpeg (Windows)
        if: runner.os == 'Windows'
        run: |
          mkdir bin
          choco install ffmpeg -y
          copy "C:\ProgramData\chocolatey\bin\ffmpeg.exe" bin\
          copy "C:\ProgramData\chocolatey\bin\ffprobe.exe" bin\

      - name: Download FFmpeg (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install ffmpeg
          mkdir -p bin
          cp "$(brew --prefix)/bin/ffmpeg" bin/ffmpeg
          cp "$(brew --prefix)/bin/ffprobe" bin/ffprobe
          chmod +x bin/ffmpeg bin/ffprobe

      - name: Build with PyInstaller
        shell: bash -l {0}
        run: pyinstaller build.spec

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AudioTTo-${{ runner.os }}
          path: dist/
